name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: SetUp Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Run Tests
        run: chmod +x gradlew && ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub