name: Test & Deploy Allure Report

on: [push]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Run Tests with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub || echo "Tests failed (ignored for report generation)"

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install allure

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          allure generate build/allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 1  # Keeps artifact for 1 day

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: /
          keep_files: true